<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('wifi_ssids', function (Blueprint $table) {
            // First, drop the foreign key constraint if it exists.
            // The name of the foreign key constraint is autogenerated by Laravel
            // and is typically in the format: table_name_column_name_foreign
            // It might be different based on the Laravel version, so we'll try a common pattern.
            // If you know the exact name, it's better to use it.
            try {
                 $table->dropForeign(['office_id']);
            } catch (\Exception $e) {
                // If the foreign key doesn't exist, it will throw an exception. We can ignore it.
            }
            $table->dropColumn('office_id');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('wifi_ssids', function (Blueprint $table) {
            // If we roll back, we add the column back.
            $table->foreignId('office_id')->nullable()->constrained()->onDelete('cascade');
        });
    }
};
